let questhtml = [
    {
        "question": "Wer hat HTML erfunden?",
        "answer1": "Jimmy Wales",
        "answer2": "Larry Page",
        "answer3": "Tim Berners-Lee",
        "answer4": "Mark Zuckerberg",
        "rightAnswer": 3,
        "question-image": "img/htmlLogo.png",

    },
    {
        "question": "Wofür steht HTML?",
        "answer1": "Hybridtext Markup Language",
        "answer2": "Hypertext Markup Language",
        "answer3": "Hyperlinks Textmarkup Language",
        "answer4": "Hypertool Markup Link",
        "rightAnswer": 2,
        "question-image": "img/htmlLogo.png",
    },
    {
        "question": "Mit welchem HTML Befehl generiert man einen Link?",
        "answer1": "< div >",
        "answer2": "< button >",
        "answer3": "< a href='#' >",
        "answer4": "< img src='#' >",
        "rightAnswer": 3,
        "question-image": "img/htmlLogo.png",

    },
    {
        "question": "Mit welchem Buchstaben kann ein Text fett geschrieben werden?",
        "answer1": "< k >",
        "answer2": "< i >",
        "answer3": "< u >",
        "answer4": "< b >",
        "rightAnswer": 4,
        "question-image": "img/htmlLogo.png",

    },
    {
        "question": "Welches Zeichen wird das beenden eines Tag's angegeben?",
        "answer1": "/",
        "answer2": ">",
        "answer3": "*/",
        "answer4": "<",
        "rightAnswer": 1,
        "question-image": "img/htmlLogo.png",
    },
    {
        "question": "Bei welchem Beispiel handelt es sich bei allen Elementen um Tabellen-Elemente?",
        "answer1": "table, body, tr",
        "answer2": "table, tr, td",
        "answer3": "table, tr, tt",
        "answer4": "thead, tbody, tfoot",
        "rightAnswer": 2,
        "question-image": "img/htmlLogo.png",
    },
]

let questcss = [
     {
        "question": "Wofür steht CSS?",
        "answer1": "Computer Style Sheet",
        "answer2": "Cascading Style Sheets",
        "answer3": "Color Style Sheet",
        "answer4": "Creative Style Sheet",
        "rightAnswer": 2,
        "question-image": "img/cssLogo.png",
    },
    {
        "question": "Mir welchem HTML Befehl wird eine CSS-Datei eingebunden?",
        "answer1": "< stylesheet=style.css>",
        "answer2": "< script scr='style.css'>",
        "answer3": "< meta content='style.css'>",
        "answer4": "< link rel='stylesheet' type='text/css' href='style.css'>",
        "rightAnswer": 4,
        "question-image": "img/cssLogo.png",
    },
    {
        "question": "Wie lautet die korrekte CSS-Syntax?",
        "answer1": "body[color{black}]",
        "answer2": "body{color:black}",
        "answer3": "body{color=black}",
        "answer4": "body{color;black}:",
        "rightAnswer": 2,
        "question-image": "img/cssLogo.png",
    },
    {
        "question": "mit welcher CSS-Eigenschaft kann die Textfarbe verändert werden?",
        "answer1": "text-color",
        "answer2": "font-color",
        "answer3": "color",
        "answer4": "tcolor",
        "rightAnswer": 3,
        "question-image": "img/cssLogo.png",
    },
    {
        "question": "Mit welcher Eigenschaft kann die Schriftart festgelegt werden?",
        "answer1": "text-style",
        "answer2": "font-family",
        "answer3": "text-family",
        "answer4": "font-style",
        "rightAnswer": 2,
        "question-image": "img/cssLogo.png",
    },
    {
        "question": "Wie kannst du auf ein Element mit der id 'text' in CSS zugreifen",
        "answer1": "#text",
        "answer2": ".text",
        "answer3": ".id='text'",
        "answer4": "*text",
        "rightAnswer": 1,
        "question-image": "img/cssLogo.png",
    },
]

let questjs = [
     {
        "question": "In welchen HTML Tag wird JavaScript geschrieben?",
        "answer1": "< js >",
        "answer2": "< script >",
        "answer3": "< javascript >",
        "answer4": "< function >",
        "rightAnswer": 2,
        "question-image": "img/jsLogo.png",
    },
    {
        "question": "Wie kann über JavaScript der HTML-Content über die ID verändert werden?",
        "answer1": "document.getElementById('text').innerHTML='';",
        "answer2": "document.getElementByName('text').innerHTML='';",
        "answer3": "#text.innerHTML='';",
        "answer4": "document.getElement('text').innerHTML='';",
        "rightAnswer": 1,
        "question-image": "img/jsLogo.png",
    },
    {
        "question": "Wie kannst du einen 'alert' schreiben",
        "answer1": "alert: 'text'",
        "answer2": "alert[text]",
        "answer3": "alert('text')",
        "answer4": "showAlert('text')",
        "rightAnswer": 3,
        "question-image": "img/jsLogo.png",
    },
    {
        "question": "Wie schreibt man eine If-Abfrage für x ist nicht gleich 7?",
        "answer1": "if (x /= 7)",
        "answer2": "if x =! 7 then",
        "answer3": "if (x < or > 7)",
        "answer4": "if (x != 7)",
        "rightAnswer": 4,
        "question-image": "img/jsLogo.png",
    },
    {
        "question": "Wie schreibt man einen JS-Array?",
        "answer1": "myArray = ([HTML], [CSS], [JS])",
        "answer2": "myArray = ['HTML','CSS','JS']",
        "answer3": "myArray = [(1='HTML'),(2='CSS'),(3='JS')]",
        "answer4": "myArray = [HTML, CSS, JS]",
        "rightAnswer": 2,
        "question-image": "img/jsLogo.png",
    },
    {
        "question": "Wie kannst du dir die <b>Variable</b> 'Name' über die Konsole ausgeben lassen?",
        "answer1": "console.log(Name)",
        "answer2": "console.load('Name')",
        "answer3": "console.show(Name)",
        "answer4": "console.log('Name')",
        "rightAnswer": 1,
        "question-image": "img/jsLogo.png",
    },
]


let questpython = [
    {
        "question": "Wie kannst du einer Variable den numerischen Wert 5 zuweisen?",
        "answer1": "number = 5",
        "answer2": "number = int(5)",
        "answer3": "x, y = 5, 5",
        "answer4": "alle Antworten sind richtig",
        "rightAnswer": 4,
        "question-image": "img/python.png",
    },
    {
        "question": "Mit welcher Syntax wird der Output 'Python' realisiert?",
        "answer1": "echo(Python)",
        "answer2": "print('Python')",
        "answer3": "output('Python')",
        "answer4": "plot.Python",
        "rightAnswer": 2,
        "question-image": "img/python.png",
    },
    {
        "question": "Welcher der folgenden Variablen-Namen ist nicht erlaubt?",
        "answer1": "MeineVariable",
        "answer2": "Meine-Variable",
        "answer3": "_Meinevariable",
        "answer4": "Meine_Variable",
        "rightAnswer": 2,
        "question-image": "img/python.png",
    },
    {
        "question": "Wie kannst du dir den Typ (zb. Zahl, string) von einer Variable ausgeben lassen?",
        "answer1": "print(type(x))",
        "answer2": "print(type_x)",
        "answer3": "print(typeOf(x))",
        "answer4": "print((type)(x))",
        "rightAnswer": 1,
        "question-image": "img/python.png",
    },
    {
        "question": "wie kann eine Funktion in Python definiert werden?",
        "answer1": "function meineFunktion():",
        "answer2": "creat meineFunktion():",
        "answer3": "def meineFunktion():",
        "answer4": "setUp meine Funktion():",
        "rightAnswer": 3,
        "question-image": "img/python.png",
    },
    {
        "question": "Wie schreibst du eine If-Abfrage in Python?",
        "answer1": "if (x < y):",
        "answer2": "if x < y :",
        "answer3": "if x < y then:",
        "answer4": "if (x < y) then:",
        "rightAnswer": 2,
        "question-image": "img/python.png",
    },
]